services:
  wcpp-registry:
    build:
      dockerfile: ./Registry/Dockerfile
    container_name: wcpp-registry
    expose:
      - "3000"
    networks:
      - corinthian
  wcpp-db:
    build:
      dockerfile: ./Database/Dockerfile
    container_name: wcpp-db
    depends_on:
      - wcpp-registry
      - postgres
    expose:
      - "3000"
    networks:
      - corinthian
  postgres:
    image: "postgres:17.2"
    container_name: postgres
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    expose:
      - "5432"
    networks:
      - corinthian
  wcpp-logic:
    build:
      dockerfile: ./Logic/Dockerfile
    container_name: wcpp-logic
    depends_on:
      - wcpp-registry
    expose:
      - "3000"
    networks:
      - corinthian
  wcpp-gateway:
    build:
      dockerfile: ./Gateway/Dockerfile
    container_name: wcpp-gateway
    depends_on:
      - wcpp-registry
      - wcpp-logic
      - wcpp-db
    expose:
      - "3000"
    ports:
      - "9080:3000"
    networks:
      - corinthian

networks:
  corinthian:
    driver: bridge
